[packages.components]
versioned_files = ["packages/components/package.json"]
changelog = "packages/components/CHANGELOG.md"
scopes = ["components"]

[packages.a11y]
versioned_files = ["packages/a11y/package.json"]
changelog = "packages/a11y/CHANGELOG.md"
scopes = ["a11y"]

[packages.elements]
versioned_files = ["packages/elements/package.json"]
changelog = "packages/elements/CHANGELOG.md"
scopes = ["elements"]

[packages.scroll-lock]
versioned_files = ["packages/scroll-lock/package.json"]
changelog = "packages/scroll-lock/CHANGELOG.md"
scopes = ["scroll-lock"]

[packages.svg-sprites]
versioned_files = ["packages/svg-sprites/package.json"]
changelog = "packages/svg-sprites/CHANGELOG.md"
scopes = ["svg-sprites"]

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"
allow_empty = true

[[workflows.steps]]
type = "Command"
command = "git add --all"
shell = true

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare releases\" || true"
shell = true

[[workflows.steps]]
type = "Release"

[[workflows.steps]]
type = "Command"
command = "task publish-packages"
shell = true

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"
