# https://taskfile.dev

version: "3"

env:
  PACKAGE_SCOPE:

tasks:
  setup:
    desc: Install dependencies
    dir: "{{.TASKFILE_DIR}}"
    sources:
      - .rtx.toml
      - "package.json"
      - "pnpm-*.yaml"
      - "**/package.json"
    cmds:
      - rtx install 2> /dev/null || true
      - bun install

  build:
    desc: Build all elements
    deps: [setup]
    cmds:
      - bun x turbo build --filter "./elements/**"

  test:
    desc: Run tests on all elements
    dir: "{{.TASKFILE_DIR}}/elements"
    deps: [build]
    cmds:
      - bun x turbo test

  lint:
    desc: Run linter on all packages
    deps: [build]
    cmds:
      - bun x turbo lint

  fix:
    cmds:
      - bun x biome format --write .
      - bun x biome lint --skip-errors --apply-unsafe .

  new:
    desc: Create a new component from templates
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x @sv/mono new

  clean:
    desc: Clean local files
    cmds:
      - git clean -xdf

  docs:
    desc: Start dev server for docs
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [build]
    cmds:
      - bun run dev

  docs:build:
    desc: Builds the docs into the public folder
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [build]
    cmds:
      - bun run build
      - mv dist ../public

  version:
    dir: "{{.TASKFILE_DIR}}/{{.PACKAGE_SCOPE}}"
    deps: [build]
    vars:
      version_file: "{{.TASKFILE_DIR}}/.task/.version"
    requires:
      vars: [type]
    cmds:
      - echo $(npm version {{.type}} --preid=rc --git-tag-version=false) > {{.version_file}}
      - git add --all
      - 'git commit -m "version: $(cat {{.version_file}})"'

  version:minor:
    desc: "Create minor version"
    cmds:
      - task: version
        vars:
          type: minor

  version:patch:
    desc: "Create patch version"
    cmds:
      - task: version
        vars:
          type: patch

  version:prerelease:
    desc: "Create prereleasae version"
    cmds:
      - task: version
        vars:
          type: prerelease

  publish:preview:
    desc: Pack the pacakge for preview
    dir: "{{.TASKFILE_DIR}}/{{.PACKAGE_SCOPE}}"
    cmds:
      - npm pack && tar -xvzf *.tgz && rm -rf package *.tgz

  publish:
    desc: Publish npm pacakge
    dir: "{{.TASKFILE_DIR}}/{{.PACKAGE_SCOPE}}"
    cmds:
      - npm publish
      - git push origin HEAD:develop -o ci.skip

  publish:dev:
    desc: Publish npm pacakge
    dir: "{{.TASKFILE_DIR}}/{{.PACKAGE_SCOPE}}"
    cmds:
      - npm publish --tag dev
      - git push origin HEAD:develop -o ci.skip
