# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  docs:
    taskfile: docs/Taskfile.yml
    dir: docs

  cli:
    taskfile: packages/components/Taskfile.yml
    dir: packages/components

tasks:
  default:
    desc: List available tasks
    silent: true
    cmds:
      - task -l --sort none

  setup:
    desc: Install tools and dependencies
    run: when_changed
    dir: "{{.TASKFILE_DIR}}"
    sources:
      - .mise.toml
      - "package.json"
      - "**/package.json"
    cmds:
      - bun install

  build:
    desc: Build all packages
    deps: [setup]
    cmds:
      - bun x turbo build --filter "./packages/**"

  dev:
    desc: Watch-build packages for development
    deps: [setup]
    cmds:
      - bun x turbo dev --filter "./packages/**"

  test:
    desc: "Run tests on all packages (Run specific test: t test --  --test-name-pattern prettier)"
    dir: "{{.TASKFILE_DIR}}"
    deps: [build]
    env:
      CI_JOB_TOKEN: "glpat-tDVjH5PFYZkPiw39ffMy"
    cmds:
      - bun x turbo test -- {{.CLI_ARGS}}

  check:
    desc: Run checks on all packages
    deps: [setup]
    cmds:
      - bun x turbo check
      - bun x biome check . --diagnostic-level=error

  fix:
    desc: Apply all (unsafe) autofixes
    cmds:
      - bun x biome check --apply .

  fix:unsafe:
      desc: Apply all (unsafe) autofixes
      cmds:
        - bun x biome check --apply-unsafe .


  clean:
    desc: Clean untracked files
    cmds:
      - git clean -xdf
      - git tag -d $(git tag -l)

  version:
    silent: true
    desc: Create a package version
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x changeset add

  version:dev:
    desc: Enter pre-release mode
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x changeset pre enter dev
      - task: version

  publish:
    deps: [build]
    vars:
      message:
        sh: "git log -1 --pretty=format:%B"
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x changeset version
      - git push origin HEAD:main -o ci.skip
      - bun x changeset publish --tag > .task/publish.txt
      - defer: rm .task/publish.txt
      - git push origin HEAD:main --tags
      - task notify || true

  format:
    cmds:
      - task: fix
      - 'git diff --exit-code && git commit -m "ci: format" || true'
      - "git push origin HEAD:{{.CI_COMMIT_REF_NAME}}"

  notify:
    silent: true
    dir: "./"
    cmds:
      - bun ./scripts/generate-notify > .task/notify.txt
      - defer: rm .task/notify.txt
      - 'echo "{\"message\": \"$(cat .task/notify.txt)\"}"'
      - 'curl -X POST -d "{\"message\": \"$(cat .task/notify.txt)\"}" $SLACK_WEBHOOK_URL'

  docker:build:
    cmds:
      - docker buildx build --platform linux/arm64/v8,linux/amd64 --push -t luckydye/mise:latest -f ./.docker/Dockerfile .
