# https://taskfile.dev

version: "3"

env:
  PACKAGE_SCOPE: .

tasks:
  run-packages:
    desc: Run a command in all packages
    internal: true
    vars:
      command: '{{.command | default "echo"}}'
      dirs:
        sh: echo $(find ./elements/packages -maxdepth 2 -type f -name "package.json" -exec dirname {} \;)
    cmds:
      - for: { var: dirs, split: " " }
        cmd: cd {{.ITEM}} && {{.command}}

  setup:
    desc: Install dependencies
    dir: "{{.TASKFILE_DIR}}"
    sources:
      - .rtx.toml
      - "package.json"
      - "pnpm-*.yaml"
      - "**/package.json"
    cmds:
      - rtx install 2> /dev/null || true
      - pnpm install

  test:
    desc: Run tests on all elements
    dir: "{{.TASKFILE_DIR}}/elements"
    deps: [build]
    cmds:
      - bun test

  lint:
    desc: Run linter on all packages
    deps: [setup]
    cmds:
      - bun x biome check .

  build:
    desc: Build all elements
    deps: [setup]
    cmds:
      - task: run-packages
        vars:
          command: bun run build

  docs:
    desc: Start dev server for docs
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [build]
    cmds:
      - bun run dev

  docs:build:
    desc: Builds the docs into the public folder
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [build]
    cmds:
      - bun run build
      - mv dist ../public

  new:
    desc: Create a new component from templates
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x @sv/mono new

  clean:
    desc: Clean local files
    cmds:
      - git clean -xdf

  version:
    dir: "{{.TASKFILE_DIR}}/{{.PACKAGE_SCOPE}}"
    deps: [build]
    vars:
      type: prerelease
    cmds:
      - npm version {{.type}} --git-tag-version=false
      - 'git add . && git commit -m "version: minor version %s"'

  version:minor:
    desc: "Create minor version"
    cmds:
      - task: version
        vars:
          type: minor

  version:patch:
    desc: "Create patch version"
    cmds:
      - task: version
        vars:
          type: patch

  version:prerelease:
    desc: "Create prereleasae version"
    cmds:
      - task: version
        vars:
          type: prerelease

  publish:preview:
    desc: Pack the pacakge for preview
    dir: "{{.TASKFILE_DIR}}/{{.PACKAGE_SCOPE}}"
    cmds:
      - npm pack && tar -xvzf *.tgz && rm -rf package *.tgz

  publish:
    desc: Publish npm pacakge
    dir: "{{.TASKFILE_DIR}}/{{.PACKAGE_SCOPE}}"
    cmds:
      - npm publish
      - git push -o ci.skip
      - git push origin HEAD:develop -o ci.skip

  publish:dev:
    desc: Publish npm pacakge
    dir: "{{.TASKFILE_DIR}}/{{.PACKAGE_SCOPE}}"
    cmds:
      - npm publish --tag dev
      - git push -o ci.skip
      - git push origin HEAD:develop -o ci.skip
