# https://taskfile.dev

version: "3"

includes:
  publish: ./npm-publish.yml

tasks:
  setup:
    desc: Install dependencies
    dir: '{{.TASKFILE_DIR}}'
    sources:
      - .rtx.toml
      - 'package.json'
      - '**/package.json'
    cmds:
      - rtx install 2> /dev/null || true
      - bun install

  test:
    desc: Run tests on all components
    deps: [setup]
    cmds:
      - task: build
      - bun test

  lint:
    desc: Run linter on all components
    deps: [setup]
    cmds:
      - bun x biome check .

  build:
    desc: Build all components
    deps: [setup]
    cmds:
      - bun x turbo build

  docs:
    desc: Start dev server for docs
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [setup]
    cmds:
      - bun dev

  docs:build:
    desc: Builds the docs into the public folder
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [setup]
    cmds:
      - task: build
      - bun build
      - mv dist ../public

  new:
    desc: Create a new component from templates
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bunx atrium new

  reset:
    desc: Clean local files
    cmds:
      - git clean -xdf
