# https://taskfile.dev

version: "3"

tasks:
  setup:
    desc: Install dependencies
    dir: '{{.TASKFILE_DIR}}'
    sources:
      - .rtx.toml
      - 'package.json'
      - '**/package.json'
    cmds:
      - rtx install 2> /dev/null || true
      - bun install

  test:
    desc: Run tests on all components
    deps: [setup]
    cmds:
      - task: build
      - bun test

  lint:
    desc: Run linter on all components
    deps: [setup]
    cmds:
      - bun x biome check .

  build:
    desc: Build all components
    deps: [setup]
    cmds:
      - bun x nx run-many -t build --exclude docs

  docs:
    desc: Start dev server for docs
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [setup]
    cmds:
      - bun --bun x astro dev

  docs:build:
    desc: Builds the docs into the public folder
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [setup]
    cmds:
      - task: build
      - bun --bun x astro build
      - mv dist ../public

  new:
    desc: Create a new component from templates
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x atrium new

  reset:
    desc: Clean local files
    cmds:
      - git clean -xdf

  publish:
    desc: Publish npm pacakge
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - task build
      - npm version patch
      - npm publish
      - git push --tags -o ci.skip
      - git push origin HEAD:main -o ci.skip
      - git push origin HEAD:develop -o ci.skip

  publish:dev:
    desc: Publish npm package to dev tag
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - task build
      - npm version prerelease
      - npm publish --tag dev
      - git push origin --tags -o ci.skip
      - git push origin HEAD:develop -o ci.ski

  publish:preview:
    desc: Pack the pacakge for preview
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - npm pack && tar -xvzf *.tgz && rm -rf package *.tgz
