# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  docs:
    taskfile: docs/Taskfile.yml
    dir: docs

tasks:
  default:
    desc: List available tasks
    silent: true
    cmds:
      - task -l --sort none

  setup:
    desc: Install tools and dependencies
    run: when_changed
    sources:
      - .mise.toml
      - "package.json"
      - "**/package.json"
    cmds:
      - bun install

  build:
    desc: Build all packages
    deps: [setup]
    cmds:
      - bun x turbo build --filter "./packages/**"

  # experimental bundle task using bun
  bundle:
    dir: "{{.USER_WORKING_DIR}}"
    vars:
      ENTRY:
        sh: cat package.json | jq -jr '.tsup.entry[] | " ",.'
      FORMAT:
        sh: cat package.json | jq -jr '.tsup.format[] | " ",.'
      EXTERNAL:
        sh: cat package.json | jq -jr '.tsup.external[] | " -e ",.'
    cmd: bun build --target=browser {{.ENTRY}} --outdir dist --sourcemap=external --format {{.FORMAT}} {{.EXTERNAL}} {{.CLI_ARGS}}

  dev:
    desc: Start docs and watch for changes
    deps: [setup]
    cmds:
      - task --parallel docs build:watch

  build:watch:
    desc: Watch-build packages for development
    deps: [setup]
    cmds:
      - bun x turbo dev --filter "./packages/**"

  test:
    desc: "Run tests on all packages (Run specific test: t test --  -t prettier)"
    deps: [build]
    cmds:
      - bun x turbo test -- {{.CLI_ARGS}}

  a11y:
    desc: "Run a11y tests"
    dir: "docs"
    deps: [setup]
    cmds:
      - 'npx @sv/a11y ./a11y.json "task preview"'

  test:watch:
    desc: "Run tests on current packages (Run specific test: t test --  -t prettier)"
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - bun test --watch -t {{.CLI_ARGS}}

  check:
    desc: Run checks on all packages
    deps: [setup]
    cmds:
      - bun x turbo check
      - bun x biome check --diagnostic-level=error .

  fix:
    desc: Apply all (unsafe) autofixes
    cmds:
      - bun x biome check --apply .

  fix:unsafe:
    desc: Apply all (unsafe) autofixes
    cmds:
      - bun x biome check --apply-unsafe .

  clean:
    desc: Clean untracked files
    cmds:
      - git clean -xdf
      - git tag -d $(git tag -l)

  version:
    silent: true
    desc: Create a package version
    cmds:
      - knope document-change
      - git add --all

  release:
    deps: [build]
    cmds:
      - knope -v release | tee .task/publish.txt
      - task notify || true

  prerelease:
    deps: [build]
    vars:
      PRERELEASE_LABEL: "dev"
    cmds:
      - PRERELEASE_LABEL={{.PRERELEASE_LABEL}} knope -v release --prerelease-label=$PRERELEASE_LABEL

  release:preview:
    cmds:
      - knope release --dry-run

  publish:
    dir: "{{.USER_WORKING_DIR}}"
    vars:
      PRERELEASE_LABEL:
        sh: echo $PRERELEASE_LABEL
      NAME:
        sh: bun x npm version --json | jq "keys[0]"
      VERSION:
        sh: bun x npm version --json | jq ".[keys[0]]"
    cmds:
      - bun x npm publish --tag {{.PRERELEASE_LABEL | default "latest"}} && echo info Publishing \"{{.NAME}}\" at \"{{.VERSION}}\" || true

  notify:
    silent: true
    dir: "./"
    cmds:
      - bun ./scripts/generate-notify > .task/notify.txt
      - defer: rm .task/notify.txt
      - 'echo "$(cat .task/notify.txt)"'
      - 'curl -X POST -d "$(cat .task/notify.txt)" $SLACK_WEBHOOK_URL'

  docker:build:
    desc: Build docker image, pass --push to push to registry
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -f .docker/Dockerfile --tag luckydye/atrium:latest . {{.CLI_ARGS}}
