# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  setup:
    desc: Install dependencies
    dir: "{{.TASKFILE_DIR}}"
    sources:
      - .rtx.toml
      - "package.json"
      - "pnpm-*.yaml"
      - "**/package.json"
    cmds:
      - rtx install 2> /dev/null || true
      - bun install

  build:
    desc: Build all packages
    deps: [setup]
    cmds:
      - bun x turbo build --filter "./packages/**"

  test:
    desc: Run tests on all packages
    dir: "{{.TASKFILE_DIR}}"
    deps: [build]
    cmds:
      - bun x turbo test

  lint:
    desc: Run linter on all packages
    deps: [build]
    cmds:
      - bun x turbo lint

  fix:
    desc: Apply all (unsafe) autofixes
    cmds:
      - bun x biome check --apply-unsafe .

  clean:
    desc: Clean untracked files
    cmds:
      - git clean -xdf
      - git tag -d $(git tag -l)

  docs:
    desc: Start dev server for docs
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [build]
    cmds:
      - bun run dev

  docs:build:
    desc: Builds the docs into the public folder
    dir: "{{.TASKFILE_DIR}}/docs"
    deps: [build]
    cmds:
      - bun run build
      - mv dist ../public

  webhook:
    requires:
      vars: [message, version, type]
    cmds:
      - 'curl -X POST -d "{\"message\": \"{{.message}}\", \"version\": \"{{.version}}\", \"type\": \"{{.type}}\"}" {{.SLACK_WEBHOOK_URL}}'

  version:
    desc: Create a package version
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x changeset
      - git add --all
      - bun x changeset status --output status.json
      - 'git commit -m "version: $(cat status.json | jq -r ".changesets[0].summary")"'
      - rm status.json
      - git push

  version:dev:
    desc: Enter pre-release mode
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x changeset pre enter dev
      - task: version

  publish:
    deps: [build]
    vars:
      message:
        sh: "git log -1 --pretty=format:%B"
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - bun x changeset version
      - bun x changeset publish --tag > publish.txt
      - git add --all
      - 'git commit -m "version: publish"'
      - git push origin HEAD:develop -o ci.skip
      - git push origin HEAD:develop --follow-tags
      - echo $(cat publish.txt)
      # - task webhook message="{{.message}}" version="$(cat package.json | jq -r .version)"
      - rm publish.txt
