# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  setup:
    desc: Install tools
    dir: "{{.TASKFILE_DIR}}"
    sources:
      - .rtx.toml
    cmds:
      - mise install

  build:
    desc: Build all packages
    deps: [setup]
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -ldflags='-s -w' -o ./packages/components-darwin-arm64/components-darwin-arm64 ./src/cli
      - GOOS=darwin GOARCH=amd64 go build -ldflags='-s -w' -o ./packages/components-darwin-x64/components-darwin-x64 ./src/cli
      - GOOS=linux GOARCH=arm64 go build -ldflags='-s -w' -o ./packages/components-linux-arm64/components-linux-arm64 ./src/cli
      - GOOS=linux GOARCH=amd64 go build -ldflags='-s -w' -o ./packages/components-linux-x64/components-linux-x64 ./src/cli
