# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  setup:
    desc: Install tools
    dir: "{{.TASKFILE_DIR}}"
    sources:
      - .rtx.toml
    cmds:
      - mise install 2> /dev/null || true

  build:
    desc: Build all packages
    deps: [setup]
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -ldflags='-s -w' -o ./dist/aarch64-darwin/components ./src/cli
      - GOOS=darwin GOARCH=amd64 go build -ldflags='-s -w' -o ./dist/x64-darwin/components ./src/cli
      - GOOS=linux GOARCH=amd64 go build -ldflags='-s -w' -o ./dist/x64-linux/components ./src/cli
