# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  setup:
    desc: Install tools
    dir: "{{.TASKFILE_DIR}}"
    sources:
      - .rtx.toml
    cmds:
      - mise install

  build:
    desc: Build all packages
    deps: [setup]
    cmds:
      - bun x tsup
